services:
  # O Servidor Web da sua aplicação Flask
  - type: web
    name: backend-chip-cia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false

  # O Cron Job que roda todo dia às 18h
  - type: cron
    name: cron-alimenta-conversas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cron_feed_conversations.py
    schedule: "0 18 * * *"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false